export const GET_HOTEL_LIST_FULFILLED = 'GET_HOTEL_LIST_FULFILLED';
export const TOGGLE_ACCOUNT_FORM = 'TOGGLE_ACCOUNT_FORM';
export const UPDATE_ACCOUNT_FORM_SIDE = 'UPDATE_ACCOUNT_FORM_SIDE';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
export const HANDLE_LOGOUT_FULFILLED = 'HANDLE_LOGOUT_FULFILLED';
