//User
export const SET_USER = 'SET_USER';
export const TOGGLE_ACCOUNT_FORM = 'TOGGLE_ACCOUNT_FORM';
export const UPDATE_ACCOUNT_FORM_SIDE = 'UPDATE_ACCOUNT_FORM_SIDE';

//Get User
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';

//Logout User
export const HANDLE_LOGOUT_PENDING = 'HANDLE_LOGOUT_PENDING';
export const HANDLE_LOGOUT_FULFILLED = 'HANDLE_LOGOUT_FULFILLED';
export const HANDLE_LOGOUT_REJECTED = 'HANDLE_LOGOUT_REJECTED';

//Non User
export const SET_SEARCH_INFO = 'SET_SEARCH_INFO';
export const GET_HOTEL_LIST_BY_ID_FULFILLED = 'GET_HOTEL_LIST_BY_ID_FULFILLED';

//Get Hotel List
export const GET_HOTEL_LIST_PENDING = 'GET_HOTEL_LIST_PENDING';
export const GET_HOTEL_LIST_FULFILLED = 'GET_HOTEL_LIST_FULFILLED';
export const GET_HOTEL_LIST_REJECTED = 'GET_HOTEL_LIST_REJECTED';
